Do not write fstab entries (bsc#1073237)
crowbar/crowbar-ceph pull request #108
Opened 2018-03-06 13:07 UTC by bmwiedemann

because it can have races with ceph-disk activate moving mounts
https://bugzilla.suse.com/show_bug.cgi?id=1073237

Also it made the whole OSD allocation less dynamic than it could be.

backport of #105

2018-03-06 13:37 UTC, nicolasbock requested changes
Please `cherry-pick -x` so we get the commit hash as references.

2018-03-06 14:36 UTC, bmwiedemann commented
@nicolasbock done

2018-03-06 15:05 UTC, dirkmueller approved these changes

2018-03-06 20:13 UTC, nicolasbock approved these changes

2018-03-08 09:46 UTC, dirkmueller commented
hmm, the segfault in ceph doesn't look good :/

2018-03-08 10:17 UTC, tserong commented
> hmm, the segfault in ceph doesn't look good :/

I'm looking at that. It's almost certainly unrelated to this change.

2018-03-22 13:49 UTC, merged