prefer class methods over instance methods for the ceph model
crowbar/crowbar-ceph pull request #72
Opened 2016-09-22 13:09 UTC by MaximilianMeister

depends on https://github.com/crowbar/crowbar-ceph/pull/71

after that I will rebase this one to have the renaming changes

2016-09-22 13:21 UTC, MaximilianMeister commented
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8X7elkka&#x2F;82-cleanup-upgrade-related-mess"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Cleanup upgrade related mess</a>

2016-09-22 13:33 UTC, jsuchome commented
+1

2016-09-26 15:15 UTC, rsalevsky requested changes
+1

But gating failed.

2016-09-26 15:15 UTC, rsalevsky approved these changes

2016-09-27 06:52 UTC, merged