ceph: try to use monitor initial members from the public network
crowbar/crowbar-ceph pull request #85
Opened 2017-01-18 13:41 UTC by mjura

2017-01-18 16:06 UTC, sidthe approved these changes

2017-01-18 16:38 UTC, dirkmueller commented on chef/cookbooks/ceph/recipes/mon.rb
> +    command "ceph --admin-daemon '/var/run/ceph/ceph-mon.#{mon_name}.asok' " \
you're changing the asok path here but don't adjust all other references in ceph/libraries/default.rb and other places

2017-01-18 16:44 UTC, rsalevsky requested changes
Can you please fix the hound issues?

2017-01-19 08:51 UTC, mjura commented on chef/cookbooks/ceph/recipes/mon.rb
> +    command "ceph --admin-daemon '/var/run/ceph/ceph-mon.#{mon_name}.asok' " \
Done

2017-01-19 08:52 UTC, mjura commented
@rsalevsky: I fixed Hound bitching comments :)

2017-01-19 09:46 UTC, mjura commented
Let

2017-01-19 09:46 UTC, closed without merging

2017-01-19 09:46 UTC, mjura commented
Let's continue in https://github.com/crowbar/crowbar-ceph/pull/84

2017-01-19 09:46 UTC, mjura commented
Let's continue in https://github.com/crowbar/crowbar-ceph/pull/84