Make sure ceph-mds role is not deployed to the cluster node.
crowbar/crowbar-ceph pull request #97
Opened 2017-06-13 11:32 UTC by jsuchome

Ever.

2017-06-13 11:42 UTC, jsuchome commented
Alternatively, we can just remove that `if mds_node.nil?` block completely, it's already unlikely that it find some node that is intended controller, but not in cluster...

2017-06-13 20:12 UTC, jsuchome commented
Oh. Manila needs ceph-mds to be deployed...

2017-06-14 07:36 UTC, tserong submitted a review, later dismissed

2017-06-14 09:47 UTC, sjamgade submitted a review, later dismissed

2017-06-14 09:56 UTC, jsuchome commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix automatic deployment of ceph roles](https://trello.com/c/F21pgJnm/310-fix-automatic-deployment-of-ceph-roles)

2017-06-15 07:38 UTC, jsuchome commented on crowbar_framework/app/models/ceph_service.rb
> +      node_is_valid_for_role(n.name, "ceph_mds") || n.roles.include?("pacemaker-cluster-member")
This is very confusing. I assume the correct name for `node_is_valid_for_role` should be `node_is_not_valid_for_role` ... it's defined here https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/app/models/service_object.rb#L442

2017-06-15 08:34 UTC, tserong submitted a review, later dismissed
I'd still like one other pair of eyes that aren't mine on the `node_is_valid_for_role(n.name, "ceph-mds")` piece :-) but LGTM.

2017-06-15 09:50 UTC, rhafer requested changes
I think for the 1st commit you should elaborate a bit more on why ```select_nodes_for_role``` is problematic. It took me a while to actually figure out which "count" number the commit message is referring to.

2017-06-15 09:50 UTC, rhafer commented on crowbar_framework/app/models/ceph_service.rb
>      calamari_nodes.reject! do |n|
Doesn't this suffer from exactly the same problem as the mds node selection? I.e. you might endup with no remaining nodes if the node returned by ```select_nodes_for_role``` is a pacemaker member? Or am I missing something?

2017-06-15 09:50 UTC, rhafer commented on crowbar_framework/app/models/ceph_service.rb
>      calamari_nodes.reject! do |n|
BTW, wouldn't it be simpler to just reject all cluster members before calling "select_nodes_for_role" and "select_node_for_mds_role" ?

2017-06-15 10:03 UTC, jsuchome commented on crowbar_framework/app/models/ceph_service.rb
>      calamari_nodes.reject! do |n|
> Doesn't this suffer from exactly the same problem as the mds node selection

You are right (although with calamari it is not such problem when it is not deployed at all)

> reject all cluster members before calling 

That's a good point

2017-06-15 10:49 UTC, rhafer approved these changes
I think this is ok now

2017-06-15 14:11 UTC, merged