Make sure ceph-mds is deployed.
crowbar/crowbar-ceph pull request #99
Opened 2017-06-22 12:53 UTC by jsuchome

As we need only one ceph-mds node, let's take it first and we can
both make sure that there's one deployed and skip those complicated
checks for conflicts using the extra method.

i know it's embarassing, 3rd PR to do the same task ...

2017-06-22 15:12 UTC, jsuchome commented
![](https://github.trello.services/images/mini-trello-icon.png) [#cloud8 Make OpenStack barclamps work for SP3](https://trello.com/c/DxMDobCg/33-cloud8-make-openstack-barclamps-work-for-sp3)

2017-06-23 01:46 UTC, tserong submitted a review, later dismissed
Simpler is good :-)

2017-06-26 06:58 UTC, Itxaka submitted a review, later dismissed

2017-06-27 09:09 UTC, jsuchome commented
Gating is failing because of https://bugzilla.suse.com/show_bug.cgi?id=1046008 , problems with ceph backend in cinder

2017-06-30 11:51 UTC, dirkmueller requested changes

2017-06-30 11:51 UTC, dirkmueller commented on crowbar_framework/app/models/ceph_service.rb
>    # ceph-mds conflicts with ceph-osd, and should not be assigned to the cluster node
can you remove those comments alongside of the function removal?

2017-06-30 12:03 UTC, jsuchome commented on crowbar_framework/app/models/ceph_service.rb
>    # ceph-mds conflicts with ceph-osd, and should not be assigned to the cluster node
done

2017-07-03 08:15 UTC, jsuchome commented
@dirkmueller your comment has been addressed...

2017-07-03 08:23 UTC, jsuchome commented
@Itxaka @tserong needs a new review after the force push...

2017-07-03 08:24 UTC, Itxaka commented
@jsuchome arent you on PTO? Go away! :P

2017-07-03 08:26 UTC, Itxaka approved these changes

2017-07-03 08:38 UTC, s-t-e-v-e-n-k approved these changes

2017-07-03 08:53 UTC, skazi0 approved these changes
lgtm

2017-07-03 11:28 UTC, tserong approved these changes

2017-07-03 12:17 UTC, dirkmueller approved these changes

2017-07-03 12:17 UTC, merged